# Generated by Django 5.0 on 2023-12-04 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fan_nomi', models.CharField(max_length=150)),
                ('imthon_joyi', models.TextField()),
                ('oqituvchi', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Savollar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('savol', models.TextField()),
                ('fan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matemapp.fan')),
            ],
        ),
    ]
