# Generated by Django 5.0 on 2023-12-04 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matemapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fan',
            name='fan_nomi',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='fan',
            name='imthon_joyi',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='fan',
            name='oqituvchi',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='savollar',
            name='savol',
            field=models.TextField(blank=True),
        ),
    ]
